### ISSUE TITLE
graph for total forts holding time is not starting at zero

### ISSUE THREAD

**Issue by Joshua2504** [mascaldotfr/CoRT#17]
The graph for the total forts holding time is, unlike all other graphs, not starting at zero, 

<img width="1341" alt="image" src="https://github.com/mascaldotfr/CoRT/assets/11087078/03b46d4e-8638-47ea-8939-31a162af9494">

**Comment by Joshua2504** [comment]
This should be better to do a comparison between the realms. See #18 

<img width="1544" alt="image" src="https://github.com/mascaldotfr/CoRT/assets/11087078/23b73fcb-ee08-40fa-a9df-37d6c4fa2dd1">

**Comment by mascaldotfr** [comment]
This has been subject to debates loooong ago, and at the beginning it was like you're showing up there.

1. Some people thinks that the current view represents more the abyssal gap between Syrtis and the rest in term of WZ activity. The graph may indeed be seen as [biased and misleading](https://en.wikipedia.org/wiki/Misleading_graph), yet people thought the original was.
2. Lack of depth on mobile; it's often difficult to see the difference between Alsius and Ignis on small screens. And that's the reason it ended up like this and will stay like this.
