### ISSUE TITLE
Integration CoR Forum

### ISSUE THREAD

**Issue by Joshua2504** [mascaldotfr/CoRT#5]
Hello, thanks so much for bringing this up!!

we have big plans with cor-forum.de as it’s basically the last alive community page for regnum. 

Are there any doubts about integrating this trainer into the forum, including battle zone countdown?

we‘re also going to translate the forum to Spanish and English, plus switching it more into a website instead of a (dead) - and removing google ads soon.

**Comment by mascaldotfr** [comment]
Hi,

You're welcome, you guys did a great jobs at maintaining it over the years !

That's the whole point of making the trainer and BZ/bosses source easily available and open, i would like to see it spread further so we don't have a single point of failure like the unexpected closure of regnumsentinel.

If i were you i would wait the 1.33.6 balance change (#4) to work on this.
